'use client'
import AdminSidebar from '@/components/adminSidebar';
import { useContext, useEffect } from 'react';
import { UserContext } from '../context/userContext';
import swal from 'sweetalert';
import { useRouter } from 'next/navigation';


export const metadata = {
  title: 'Administra tu tienda',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const router = useRouter()

  const { logged ,user} = useContext(UserContext)


  useEffect(() => {
    // Check if user is logged in
    if (logged){
      // If yes, check if user is admin
      if (user.isAdmin){
        // If yes, proceed
      }
      else {
        // If not, redirect to home page
        swal('No tienes permisos para acceder a esta pagina', 'Por favor inicia sesion como administrador', 'error')
        router.push('/');
      }

    }
    // If not, redirect to login page
    else {
        swal('No tienes permisos para acceder a esta pagina', 'Por favor inicia sesion como administrador', 'error')
        router.push('/');
    }
  }, []);



  return (
      <div className="flex admin-main-container">
        <AdminSidebar />
        <div className="admin-content-container">

          {children}
        </div>
      </div>
  );
}